# Generated by Django 5.0 on 2023-12-17 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='created_date',
            new_name='create_date',
        ),
    ]
